#!/bin/bash
#This script updates the project from linux full source folder
#Tested on linux version 4.0.x
#Notes:
#1)Add a location parameter to search , remove hard-write path ~/...
echo "Updating project...."
echo "/kernel/sched"
cp ~/linux-stable/kernel/sched/ss.c ~/SScheduler/kernel/sched/ss.c
echo -e "\t ss.c   \t[OK]"
cp ~/linux-stable/kernel/sched/sched.h ~/SScheduler/kernel/sched/sched.h
echo -e "\t sched.h \t[OK]"
cp ~/linux-stable/kernel/sched/core.c ~/SScheduler/kernel/sched/core.c
echo -e "\t core.c \t[OK]"


echo "/arch/x86"
cp ~/linux-stable/arch/x86/Kconfig ~/SScheduler/arch/x86/Kconfig
echo -e "\t Kconfig   \t[OK]"

echo "/include/linux"
cp ~/linux-stable/include/linux/sched.h ~/SScheduler/include/linux/sched.h
echo -e "\t sched.h   \t[OK]"


echo "/include/uapi/linux"
cp ~/linux-stable/include/uapi/linux/sched.h ~/SScheduler/include/uapi/linux/sched.h
echo -e "\t sched.h   \t[OK]"



git status
git add *
